FROM golang:1.24-alpine

# Set the working directory inside the container.
WORKDIR /app

# Turn off VCS stamping globally
ENV GOFLAGS=-buildvcs=false

RUN apk update

RUN apk add --no-cache git build-base cmake gmp-dev

RUN git clone https://github.com/dense-identity/bbsgroupsig.git && \
    cd bbsgroupsig && \
    git checkout bindings/go/v1.0.5 && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . --target install && \
    cd ../.. && \
    rm -rf bbsgroupsig 

# Install air for live-reloading.
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum files to leverage Docker cache.
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of your application's source code into the container.
COPY . .

# Expose the gRPC port.
EXPOSE 50051

CMD ["air"]
