// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: relay/v1/relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type RelayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	CorrId        string                 `protobuf:"bytes,2,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessage) Reset() {
	*x = RelayMessage{}
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessage) ProtoMessage() {}

func (x *RelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessage.ProtoReflect.Descriptor instead.
func (*RelayMessage) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RelayMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RelayMessage) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

func (x *RelayMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RelayMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Ticket        []byte                 `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Message       *RelayMessage          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *PublishRequest) GetMessage() *RelayMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RelayAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=relay_at,json=relayAt,proto3" json:"relay_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *PublishResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublishResponse) GetRelayAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RelayAt
	}
	return nil
}

var File_relay_v1_relay_proto protoreflect.FileDescriptor

const file_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x14relay/v1/relay.proto\x12\x10denseid.relay.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\"t\n" +
	"\fRelayMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\acorr_id\x18\x02 \x01(\tR\x06corrId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"x\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\fR\x06ticket\x128\n" +
	"\amessage\x18\x03 \x01(\v2\x1e.denseid.relay.v1.RelayMessageR\amessage\"`\n" +
	"\x0fPublishResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x125\n" +
	"\brelay_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\arelayAt2\xb1\x01\n" +
	"\fRelayService\x12N\n" +
	"\aPublish\x12 .denseid.relay.v1.PublishRequest\x1a!.denseid.relay.v1.PublishResponse\x12Q\n" +
	"\tSubscribe\x12\".denseid.relay.v1.SubscribeRequest\x1a\x1e.denseid.relay.v1.RelayMessage0\x01B;Z9github.com/dense-identity/denseid/api/go/relay/v1;relaypbb\x06proto3"

var (
	file_relay_v1_relay_proto_rawDescOnce sync.Once
	file_relay_v1_relay_proto_rawDescData []byte
)

func file_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)))
	})
	return file_relay_v1_relay_proto_rawDescData
}

var file_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_relay_v1_relay_proto_goTypes = []any{
	(*SubscribeRequest)(nil),      // 0: denseid.relay.v1.SubscribeRequest
	(*RelayMessage)(nil),          // 1: denseid.relay.v1.RelayMessage
	(*PublishRequest)(nil),        // 2: denseid.relay.v1.PublishRequest
	(*PublishResponse)(nil),       // 3: denseid.relay.v1.PublishResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_relay_v1_relay_proto_depIdxs = []int32{
	1, // 0: denseid.relay.v1.PublishRequest.message:type_name -> denseid.relay.v1.RelayMessage
	4, // 1: denseid.relay.v1.PublishResponse.relay_at:type_name -> google.protobuf.Timestamp
	2, // 2: denseid.relay.v1.RelayService.Publish:input_type -> denseid.relay.v1.PublishRequest
	0, // 3: denseid.relay.v1.RelayService.Subscribe:input_type -> denseid.relay.v1.SubscribeRequest
	3, // 4: denseid.relay.v1.RelayService.Publish:output_type -> denseid.relay.v1.PublishResponse
	1, // 5: denseid.relay.v1.RelayService.Subscribe:output_type -> denseid.relay.v1.RelayMessage
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_relay_v1_relay_proto_init() }
func file_relay_v1_relay_proto_init() {
	if File_relay_v1_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_relay_v1_relay_proto_depIdxs,
		MessageInfos:      file_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_relay_v1_relay_proto = out.File
	file_relay_v1_relay_proto_goTypes = nil
	file_relay_v1_relay_proto_depIdxs = nil
}
