// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: relay/v1/relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayRequest_Type int32

const (
	RelayRequest_TYPE_UNSPECIFIED RelayRequest_Type = 0
	RelayRequest_PUBLISH          RelayRequest_Type = 1
	RelayRequest_SUBSCRIBE        RelayRequest_Type = 2
)

// Enum value maps for RelayRequest_Type.
var (
	RelayRequest_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "PUBLISH",
		2: "SUBSCRIBE",
	}
	RelayRequest_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"PUBLISH":          1,
		"SUBSCRIBE":        2,
	}
)

func (x RelayRequest_Type) Enum() *RelayRequest_Type {
	p := new(RelayRequest_Type)
	*p = x
	return p
}

func (x RelayRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (RelayRequest_Type) Type() protoreflect.EnumType {
	return &file_relay_v1_relay_proto_enumTypes[0]
}

func (x RelayRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayRequest_Type.Descriptor instead.
func (RelayRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{0, 0}
}

type RelayResponse_Type int32

const (
	RelayResponse_TYPE_UNSPECIFIED RelayResponse_Type = 0
	RelayResponse_EVENT            RelayResponse_Type = 1
	RelayResponse_ERROR            RelayResponse_Type = 2
)

// Enum value maps for RelayResponse_Type.
var (
	RelayResponse_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "EVENT",
		2: "ERROR",
	}
	RelayResponse_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"EVENT":            1,
		"ERROR":            2,
	}
)

func (x RelayResponse_Type) Enum() *RelayResponse_Type {
	p := new(RelayResponse_Type)
	*p = x
	return p
}

func (x RelayResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v1_relay_proto_enumTypes[1].Descriptor()
}

func (RelayResponse_Type) Type() protoreflect.EnumType {
	return &file_relay_v1_relay_proto_enumTypes[1]
}

func (x RelayResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayResponse_Type.Descriptor instead.
func (RelayResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{1, 0}
}

// ************* CLIENT → SERVER *************
type RelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                  // required; used for self-echo suppression and replay filtering
	Type          RelayRequest_Type      `protobuf:"varint,2,opt,name=type,proto3,enum=denseid.relay.v1.RelayRequest_Type" json:"type,omitempty"` // PUBLISH | SUBSCRIBE
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                                        // target topic (all ops)
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                                    // body for PUBLISH; optional one-shot publish on SUBSCRIBE
	Ticket        []byte                 `protobuf:"bytes,6,opt,name=ticket,proto3" json:"ticket,omitempty"`                                      // required for SUBSCRIBE (costs 1 token); ignored for PUBLISH
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RelayRequest) GetType() RelayRequest_Type {
	if x != nil {
		return x.Type
	}
	return RelayRequest_TYPE_UNSPECIFIED
}

func (x *RelayRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RelayRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelayRequest) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// ************* SERVER → CLIENT *************
type RelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RelayResponse_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=denseid.relay.v1.RelayResponse_Type" json:"type,omitempty"` // EVENT | ERROR
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // set on EVENT
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`      // set on ERROR (e.g., 3 INVALID_ARGUMENT, 7 PERMISSION_DENIED)
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // set on ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetType() RelayResponse_Type {
	if x != nil {
		return x.Type
	}
	return RelayResponse_TYPE_UNSPECIFIED
}

func (x *RelayResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RelayResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelayResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RelayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_relay_v1_relay_proto protoreflect.FileDescriptor

const file_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x14relay/v1/relay.proto\x12\x10denseid.relay.v1\"\xe6\x01\n" +
	"\fRelayRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.denseid.relay.v1.RelayRequest.TypeR\x04type\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x16\n" +
	"\x06ticket\x18\x06 \x01(\fR\x06ticket\"8\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPUBLISH\x10\x01\x12\r\n" +
	"\tSUBSCRIBE\x10\x02\"\xdb\x01\n" +
	"\rRelayResponse\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.denseid.relay.v1.RelayResponse.TypeR\x04type\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"2\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x022]\n" +
	"\fRelayService\x12M\n" +
	"\x06Tunnel\x12\x1e.denseid.relay.v1.RelayRequest\x1a\x1f.denseid.relay.v1.RelayResponse(\x010\x01B;Z9github.com/dense-identity/denseid/api/go/relay/v1;relaypbb\x06proto3"

var (
	file_relay_v1_relay_proto_rawDescOnce sync.Once
	file_relay_v1_relay_proto_rawDescData []byte
)

func file_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)))
	})
	return file_relay_v1_relay_proto_rawDescData
}

var file_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relay_v1_relay_proto_goTypes = []any{
	(RelayRequest_Type)(0),  // 0: denseid.relay.v1.RelayRequest.Type
	(RelayResponse_Type)(0), // 1: denseid.relay.v1.RelayResponse.Type
	(*RelayRequest)(nil),    // 2: denseid.relay.v1.RelayRequest
	(*RelayResponse)(nil),   // 3: denseid.relay.v1.RelayResponse
}
var file_relay_v1_relay_proto_depIdxs = []int32{
	0, // 0: denseid.relay.v1.RelayRequest.type:type_name -> denseid.relay.v1.RelayRequest.Type
	1, // 1: denseid.relay.v1.RelayResponse.type:type_name -> denseid.relay.v1.RelayResponse.Type
	2, // 2: denseid.relay.v1.RelayService.Tunnel:input_type -> denseid.relay.v1.RelayRequest
	3, // 3: denseid.relay.v1.RelayService.Tunnel:output_type -> denseid.relay.v1.RelayResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_relay_v1_relay_proto_init() }
func file_relay_v1_relay_proto_init() {
	if File_relay_v1_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_relay_v1_relay_proto = out.File
	file_relay_v1_relay_proto_goTypes = nil
	file_relay_v1_relay_proto_depIdxs = nil
}
