// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: keyderivation/v1/keyderivation.proto

package keyderivationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlindedElement []byte                 `protobuf:"bytes,1,opt,name=blinded_element,json=blindedElement,proto3" json:"blinded_element,omitempty"`
	Ticket         []byte                 `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_keyderivation_v1_keyderivation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyderivation_v1_keyderivation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_keyderivation_v1_keyderivation_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetBlindedElement() []byte {
	if x != nil {
		return x.BlindedElement
	}
	return nil
}

func (x *EvaluateRequest) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type EvaluateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EvaluatedElement []byte                 `protobuf:"bytes,1,opt,name=evaluated_element,json=evaluatedElement,proto3" json:"evaluated_element,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_keyderivation_v1_keyderivation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyderivation_v1_keyderivation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_keyderivation_v1_keyderivation_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetEvaluatedElement() []byte {
	if x != nil {
		return x.EvaluatedElement
	}
	return nil
}

var File_keyderivation_v1_keyderivation_proto protoreflect.FileDescriptor

const file_keyderivation_v1_keyderivation_proto_rawDesc = "" +
	"\n" +
	"$keyderivation/v1/keyderivation.proto\x12\x18denseid.keyderivation.v1\"R\n" +
	"\x0fEvaluateRequest\x12'\n" +
	"\x0fblinded_element\x18\x01 \x01(\fR\x0eblindedElement\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\fR\x06ticket\"?\n" +
	"\x10EvaluateResponse\x12+\n" +
	"\x11evaluated_element\x18\x01 \x01(\fR\x10evaluatedElement2y\n" +
	"\x14KeyDerivationService\x12a\n" +
	"\bEvaluate\x12).denseid.keyderivation.v1.EvaluateRequest\x1a*.denseid.keyderivation.v1.EvaluateResponseBKZIgithub.com/dense-identity/denseid/api/go/keyderivation/v1;keyderivationpbb\x06proto3"

var (
	file_keyderivation_v1_keyderivation_proto_rawDescOnce sync.Once
	file_keyderivation_v1_keyderivation_proto_rawDescData []byte
)

func file_keyderivation_v1_keyderivation_proto_rawDescGZIP() []byte {
	file_keyderivation_v1_keyderivation_proto_rawDescOnce.Do(func() {
		file_keyderivation_v1_keyderivation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyderivation_v1_keyderivation_proto_rawDesc), len(file_keyderivation_v1_keyderivation_proto_rawDesc)))
	})
	return file_keyderivation_v1_keyderivation_proto_rawDescData
}

var file_keyderivation_v1_keyderivation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_keyderivation_v1_keyderivation_proto_goTypes = []any{
	(*EvaluateRequest)(nil),  // 0: denseid.keyderivation.v1.EvaluateRequest
	(*EvaluateResponse)(nil), // 1: denseid.keyderivation.v1.EvaluateResponse
}
var file_keyderivation_v1_keyderivation_proto_depIdxs = []int32{
	0, // 0: denseid.keyderivation.v1.KeyDerivationService.Evaluate:input_type -> denseid.keyderivation.v1.EvaluateRequest
	1, // 1: denseid.keyderivation.v1.KeyDerivationService.Evaluate:output_type -> denseid.keyderivation.v1.EvaluateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keyderivation_v1_keyderivation_proto_init() }
func file_keyderivation_v1_keyderivation_proto_init() {
	if File_keyderivation_v1_keyderivation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyderivation_v1_keyderivation_proto_rawDesc), len(file_keyderivation_v1_keyderivation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keyderivation_v1_keyderivation_proto_goTypes,
		DependencyIndexes: file_keyderivation_v1_keyderivation_proto_depIdxs,
		MessageInfos:      file_keyderivation_v1_keyderivation_proto_msgTypes,
	}.Build()
	File_keyderivation_v1_keyderivation_proto = out.File
	file_keyderivation_v1_keyderivation_proto_goTypes = nil
	file_keyderivation_v1_keyderivation_proto_depIdxs = nil
}
