// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: keyderivation/v1/keyderivation.proto

package keyderivationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyDerivationService_Evaluate_FullMethodName = "/denseid.keyderivation.v1.KeyDerivationService/Evaluate"
)

// KeyDerivationServiceClient is the client API for KeyDerivationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for one-round OPRF evaluations.
type KeyDerivationServiceClient interface {
	// Evaluate a single blinded element and return the PRF output.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
}

type keyDerivationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyDerivationServiceClient(cc grpc.ClientConnInterface) KeyDerivationServiceClient {
	return &keyDerivationServiceClient{cc}
}

func (c *keyDerivationServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, KeyDerivationService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyDerivationServiceServer is the server API for KeyDerivationService service.
// All implementations must embed UnimplementedKeyDerivationServiceServer
// for forward compatibility.
//
// Service for one-round OPRF evaluations.
type KeyDerivationServiceServer interface {
	// Evaluate a single blinded element and return the PRF output.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	mustEmbedUnimplementedKeyDerivationServiceServer()
}

// UnimplementedKeyDerivationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyDerivationServiceServer struct{}

func (UnimplementedKeyDerivationServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedKeyDerivationServiceServer) mustEmbedUnimplementedKeyDerivationServiceServer() {}
func (UnimplementedKeyDerivationServiceServer) testEmbeddedByValue()                              {}

// UnsafeKeyDerivationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyDerivationServiceServer will
// result in compilation errors.
type UnsafeKeyDerivationServiceServer interface {
	mustEmbedUnimplementedKeyDerivationServiceServer()
}

func RegisterKeyDerivationServiceServer(s grpc.ServiceRegistrar, srv KeyDerivationServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyDerivationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyDerivationService_ServiceDesc, srv)
}

func _KeyDerivationService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyDerivationServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyDerivationService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyDerivationServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyDerivationService_ServiceDesc is the grpc.ServiceDesc for KeyDerivationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyDerivationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "denseid.keyderivation.v1.KeyDerivationService",
	HandlerType: (*KeyDerivationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _KeyDerivationService_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyderivation/v1/keyderivation.proto",
}
