// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: enrollment/v1/enrollment.proto

package enrollmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnrollmentRequest contains the serialized DIA enrollment request.
// All cryptographic details (keys, signatures, tickets, identity info)
// are encoded within dia_request by the DIA library.
type EnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiaRequest    []byte                 `protobuf:"bytes,1,opt,name=dia_request,json=diaRequest,proto3" json:"dia_request,omitempty"` // Serialized DIA enrollment request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_enrollment_v1_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_v1_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_v1_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollmentRequest) GetDiaRequest() []byte {
	if x != nil {
		return x.DiaRequest
	}
	return nil
}

// EnrollmentResponse contains the serialized DIA enrollment response.
// All enrollment data (credentials, tickets, expiration, public keys)
// are encoded within dia_response by the DIA library.
type EnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiaResponse   []byte                 `protobuf:"bytes,1,opt,name=dia_response,json=diaResponse,proto3" json:"dia_response,omitempty"` // Serialized DIA enrollment response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_enrollment_v1_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_v1_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_v1_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollmentResponse) GetDiaResponse() []byte {
	if x != nil {
		return x.DiaResponse
	}
	return nil
}

var File_enrollment_v1_enrollment_proto protoreflect.FileDescriptor

const file_enrollment_v1_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x1eenrollment/v1/enrollment.proto\x12\x15denseid.enrollment.v1\"4\n" +
	"\x11EnrollmentRequest\x12\x1f\n" +
	"\vdia_request\x18\x01 \x01(\fR\n" +
	"diaRequest\"7\n" +
	"\x12EnrollmentResponse\x12!\n" +
	"\fdia_response\x18\x01 \x01(\fR\vdiaResponse2|\n" +
	"\x11EnrollmentService\x12g\n" +
	"\x10EnrollSubscriber\x12(.denseid.enrollment.v1.EnrollmentRequest\x1a).denseid.enrollment.v1.EnrollmentResponseBEZCgithub.com/dense-identity/denseid/api/go/enrollment/v1;enrollmentpbb\x06proto3"

var (
	file_enrollment_v1_enrollment_proto_rawDescOnce sync.Once
	file_enrollment_v1_enrollment_proto_rawDescData []byte
)

func file_enrollment_v1_enrollment_proto_rawDescGZIP() []byte {
	file_enrollment_v1_enrollment_proto_rawDescOnce.Do(func() {
		file_enrollment_v1_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrollment_v1_enrollment_proto_rawDesc), len(file_enrollment_v1_enrollment_proto_rawDesc)))
	})
	return file_enrollment_v1_enrollment_proto_rawDescData
}

var file_enrollment_v1_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enrollment_v1_enrollment_proto_goTypes = []any{
	(*EnrollmentRequest)(nil),  // 0: denseid.enrollment.v1.EnrollmentRequest
	(*EnrollmentResponse)(nil), // 1: denseid.enrollment.v1.EnrollmentResponse
}
var file_enrollment_v1_enrollment_proto_depIdxs = []int32{
	0, // 0: denseid.enrollment.v1.EnrollmentService.EnrollSubscriber:input_type -> denseid.enrollment.v1.EnrollmentRequest
	1, // 1: denseid.enrollment.v1.EnrollmentService.EnrollSubscriber:output_type -> denseid.enrollment.v1.EnrollmentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enrollment_v1_enrollment_proto_init() }
func file_enrollment_v1_enrollment_proto_init() {
	if File_enrollment_v1_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrollment_v1_enrollment_proto_rawDesc), len(file_enrollment_v1_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrollment_v1_enrollment_proto_goTypes,
		DependencyIndexes: file_enrollment_v1_enrollment_proto_depIdxs,
		MessageInfos:      file_enrollment_v1_enrollment_proto_msgTypes,
	}.Build()
	File_enrollment_v1_enrollment_proto = out.File
	file_enrollment_v1_enrollment_proto_goTypes = nil
	file_enrollment_v1_enrollment_proto_depIdxs = nil
}
