// Specifies that we are using the proto3 syntax.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: enrollment/enrollment.proto

// Defines a package name to prevent name collisions between different projects.

package enrollment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisplayInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The primary name to be displayed for the entity (e.g., "Acme Corp" or "John Doe").
	// VALIDATION: This field is required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A URL pointing to a logo image.
	LogoUrl string `protobuf:"bytes,2,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	// A URL for the entity's primary website.
	WebsiteUrl string `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	// A primary brand color, represented as a hex string (e.g., "#FFFFFF").
	BrandColor string `protobuf:"bytes,4,opt,name=brand_color,json=brandColor,proto3" json:"brand_color,omitempty"`
	// A short description or tagline.
	Tagline       string `protobuf:"bytes,5,opt,name=tagline,proto3" json:"tagline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayInformation) Reset() {
	*x = DisplayInformation{}
	mi := &file_enrollment_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayInformation) ProtoMessage() {}

func (x *DisplayInformation) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayInformation.ProtoReflect.Descriptor instead.
func (*DisplayInformation) Descriptor() ([]byte, []int) {
	return file_enrollment_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DisplayInformation) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *DisplayInformation) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *DisplayInformation) GetBrandColor() string {
	if x != nil {
		return x.BrandColor
	}
	return ""
}

func (x *DisplayInformation) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

// The request message for enrolling a subscriber.
type EnrollmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The telephone number for the subscriber.
	// VALIDATION: This field is required.
	Tn string `protobuf:"bytes,1,opt,name=tn,proto3" json:"tn,omitempty"`
	// A list of public keys in hex format.
	// VALIDATION: Must contain at least one public key.
	PublicKeys []string `protobuf:"bytes,2,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	// An object containing display information like a name.
	// VALIDATION: This field is required.
	Iden *DisplayInformation `protobuf:"bytes,3,opt,name=iden,proto3" json:"iden,omitempty"`
	// The number of biometric parameters provided. Can be 0 or more.
	NB uint32 `protobuf:"varint,4,opt,name=n_b,json=nB,proto3" json:"n_b,omitempty"`
	// A list of signatures.
	// VALIDATION: The number of signatures must match the number of public keys.
	Sigs          []string `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_enrollment_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollmentRequest) GetTn() string {
	if x != nil {
		return x.Tn
	}
	return ""
}

func (x *EnrollmentRequest) GetPublicKeys() []string {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *EnrollmentRequest) GetIden() *DisplayInformation {
	if x != nil {
		return x.Iden
	}
	return nil
}

func (x *EnrollmentRequest) GetNB() uint32 {
	if x != nil {
		return x.NB
	}
	return 0
}

func (x *EnrollmentRequest) GetSigs() []string {
	if x != nil {
		return x.Sigs
	}
	return nil
}

// Nested message for the response signatures.
type Signatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig1          string                 `protobuf:"bytes,1,opt,name=sig1,proto3" json:"sig1,omitempty"`
	Sig2          string                 `protobuf:"bytes,2,opt,name=sig2,proto3" json:"sig2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signatures) Reset() {
	*x = Signatures{}
	mi := &file_enrollment_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signatures) ProtoMessage() {}

func (x *Signatures) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signatures.ProtoReflect.Descriptor instead.
func (*Signatures) Descriptor() ([]byte, []int) {
	return file_enrollment_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *Signatures) GetSig1() string {
	if x != nil {
		return x.Sig1
	}
	return ""
}

func (x *Signatures) GetSig2() string {
	if x != nil {
		return x.Sig2
	}
	return ""
}

// The response message for an enrollment request.
type EnrollmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique enrollment ID.
	Eid string `protobuf:"bytes,1,opt,name=eid,proto3" json:"eid,omitempty"`
	// The expiration timestamp for the enrollment.
	Exp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`
	// The user secret key.
	Usk string `protobuf:"bytes,3,opt,name=usk,proto3" json:"usk,omitempty"`
	// Signatures generated during the enrollment process.
	Sigs          *Signatures `protobuf:"bytes,4,opt,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_enrollment_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollmentResponse) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

func (x *EnrollmentResponse) GetExp() *timestamppb.Timestamp {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *EnrollmentResponse) GetUsk() string {
	if x != nil {
		return x.Usk
	}
	return ""
}

func (x *EnrollmentResponse) GetSigs() *Signatures {
	if x != nil {
		return x.Sigs
	}
	return nil
}

var File_enrollment_enrollment_proto protoreflect.FileDescriptor

const file_enrollment_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x1benrollment/enrollment.proto\x12\n" +
	"enrollment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x12DisplayInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x02 \x01(\tR\alogoUrl\x12\x1f\n" +
	"\vwebsite_url\x18\x03 \x01(\tR\n" +
	"websiteUrl\x12\x1f\n" +
	"\vbrand_color\x18\x04 \x01(\tR\n" +
	"brandColor\x12\x18\n" +
	"\atagline\x18\x05 \x01(\tR\atagline\"\x9d\x01\n" +
	"\x11EnrollmentRequest\x12\x0e\n" +
	"\x02tn\x18\x01 \x01(\tR\x02tn\x12\x1f\n" +
	"\vpublic_keys\x18\x02 \x03(\tR\n" +
	"publicKeys\x122\n" +
	"\x04iden\x18\x03 \x01(\v2\x1e.enrollment.DisplayInformationR\x04iden\x12\x0f\n" +
	"\x03n_b\x18\x04 \x01(\rR\x02nB\x12\x12\n" +
	"\x04sigs\x18\x05 \x03(\tR\x04sigs\"4\n" +
	"\n" +
	"Signatures\x12\x12\n" +
	"\x04sig1\x18\x01 \x01(\tR\x04sig1\x12\x12\n" +
	"\x04sig2\x18\x02 \x01(\tR\x04sig2\"\x92\x01\n" +
	"\x12EnrollmentResponse\x12\x10\n" +
	"\x03eid\x18\x01 \x01(\tR\x03eid\x12,\n" +
	"\x03exp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03exp\x12\x10\n" +
	"\x03usk\x18\x03 \x01(\tR\x03usk\x12*\n" +
	"\x04sigs\x18\x04 \x01(\v2\x16.enrollment.SignaturesR\x04sigs2f\n" +
	"\x11EnrollmentService\x12Q\n" +
	"\x10EnrollSubscriber\x12\x1d.enrollment.EnrollmentRequest\x1a\x1e.enrollment.EnrollmentResponseB8Z6github.com/dense-identity/denseid/api/proto/enrollmentb\x06proto3"

var (
	file_enrollment_enrollment_proto_rawDescOnce sync.Once
	file_enrollment_enrollment_proto_rawDescData []byte
)

func file_enrollment_enrollment_proto_rawDescGZIP() []byte {
	file_enrollment_enrollment_proto_rawDescOnce.Do(func() {
		file_enrollment_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrollment_enrollment_proto_rawDesc), len(file_enrollment_enrollment_proto_rawDesc)))
	})
	return file_enrollment_enrollment_proto_rawDescData
}

var file_enrollment_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_enrollment_enrollment_proto_goTypes = []any{
	(*DisplayInformation)(nil),    // 0: enrollment.DisplayInformation
	(*EnrollmentRequest)(nil),     // 1: enrollment.EnrollmentRequest
	(*Signatures)(nil),            // 2: enrollment.Signatures
	(*EnrollmentResponse)(nil),    // 3: enrollment.EnrollmentResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_enrollment_enrollment_proto_depIdxs = []int32{
	0, // 0: enrollment.EnrollmentRequest.iden:type_name -> enrollment.DisplayInformation
	4, // 1: enrollment.EnrollmentResponse.exp:type_name -> google.protobuf.Timestamp
	2, // 2: enrollment.EnrollmentResponse.sigs:type_name -> enrollment.Signatures
	1, // 3: enrollment.EnrollmentService.EnrollSubscriber:input_type -> enrollment.EnrollmentRequest
	3, // 4: enrollment.EnrollmentService.EnrollSubscriber:output_type -> enrollment.EnrollmentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_enrollment_enrollment_proto_init() }
func file_enrollment_enrollment_proto_init() {
	if File_enrollment_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrollment_enrollment_proto_rawDesc), len(file_enrollment_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrollment_enrollment_proto_goTypes,
		DependencyIndexes: file_enrollment_enrollment_proto_depIdxs,
		MessageInfos:      file_enrollment_enrollment_proto_msgTypes,
	}.Build()
	File_enrollment_enrollment_proto = out.File
	file_enrollment_enrollment_proto_goTypes = nil
	file_enrollment_enrollment_proto_depIdxs = nil
}
