#!/usr/bin/env bash
set -euo pipefail

# Script to generate .env.ctrl for controller.sh
# This extracts client IPs, relay address from hosts.yml and sets defaults.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
HOSTS_YML="$ROOT_DIR/infras/hosts.yml"
OUTPUT_FILE="$ROOT_DIR/.env.ctrl"

FORCE=0
RELAY_ADDR_OVERRIDE=""
REDIS_ADDR_OVERRIDE=""

usage() {
  cat <<EOF
Usage: $0 [options]

Generates .env.ctrl with controller environment variables by reading
infras/hosts.yml and applying defaults.

Options:
  --relay-addr <host:port>    Override relay address (default: auto from hosts.yml or localhost:50052)
  --redis-addr <host:port>    Override Redis address (default: localhost:6379)
  --force                     Regenerate even if .env.ctrl exists
  -h, --help                  Show this help

Example:
  $0
  $0 --force
  $0 --relay-addr 10.0.0.5:50052
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --relay-addr)
      RELAY_ADDR_OVERRIDE="$2"
      shift 2
      ;;
    --redis-addr)
      REDIS_ADDR_OVERRIDE="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Error: Unknown option $1" >&2
      usage
      ;;
  esac
done

if [[ $FORCE -eq 0 && -f "$OUTPUT_FILE" ]]; then
  echo "[create-ctrl-env] .env.ctrl already exists. Use --force to regenerate." >&2
  exit 0
fi

# Extract ansible_host for a given host name from hosts.yml.
get_ansible_host() {
  local host_name="$1"
  if [[ ! -f "$HOSTS_YML" ]]; then
    return 1
  fi
  awk -v host="$host_name" '
    $1 == host":" { in_block=1; next }
    in_block && $1 == "ansible_host:" { print $2; exit }
    in_block && $1 ~ /^[a-zA-Z0-9_-]+:$/ { in_block=0 }
  ' "$HOSTS_YML"
}

# Resolve client IPs
CLIENT_1_IP="$(get_ansible_host client-1 || echo "localhost")"
CLIENT_2_IP="$(get_ansible_host client-2 || echo "localhost")"

# Resolve relay address
if [[ -n "$RELAY_ADDR_OVERRIDE" ]]; then
  RELAY_ADDR="$RELAY_ADDR_OVERRIDE"
else
  RELAY_IP="$(get_ansible_host server || get_ansible_host relay || echo "localhost")"
  RELAY_ADDR="${RELAY_IP}:50052"
fi

# Redis address
if [[ -n "$REDIS_ADDR_OVERRIDE" ]]; then
  REDIS_ADDR="$REDIS_ADDR_OVERRIDE"
else
  REDIS_ADDR="localhost:6379"
fi

# Write .env.ctrl
cat > "$OUTPUT_FILE" <<EOF
# Controller environment (generated by scripts/create-ctrl-env.sh)
# Do not edit manually; regenerate with --force if needed.

# Client baresip addresses (from hosts.yml)
CLIENT_1_ADDR=${CLIENT_1_IP}:4444
CLIENT_2_ADDR=${CLIENT_2_IP}:4444

# Relay address (from hosts.yml server/relay or override)
RELAY_ADDR=${RELAY_ADDR}

# Redis configuration
REDIS_ADDR=${REDIS_ADDR}
REDIS_USER=
REDIS_PASS=
REDIS_DB=0
REDIS_PREFIX=denseid:dia:peer_session:v1
PEER_SESSION_TTL=0

# Defaults
BARESIP_PORT=4444
RELAY_PORT=50052
DEFAULT_ODA_ATTRS=name,issuer
DEFAULT_CSV_DIR=./results
DEFAULT_INTER_ATTEMPT_MS=1000
EOF

echo "[create-ctrl-env] Generated $OUTPUT_FILE"
echo "[create-ctrl-env]   RELAY_ADDR=$RELAY_ADDR"
echo "[create-ctrl-env]   REDIS_ADDR=$REDIS_ADDR"
echo "[create-ctrl-env]   CLIENT_1_ADDR=${CLIENT_1_IP}:4444"
echo "[create-ctrl-env]   CLIENT_2_ADDR=${CLIENT_2_IP}:4444"
