// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: revocation/v1/revocation.proto

package revocationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RevocationService_Query_FullMethodName = "/denseid.revocation.v1.RevocationService/Query"
)

// RevocationServiceClient is the client API for RevocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevocationServiceClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type revocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRevocationServiceClient(cc grpc.ClientConnInterface) RevocationServiceClient {
	return &revocationServiceClient{cc}
}

func (c *revocationServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, RevocationService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevocationServiceServer is the server API for RevocationService service.
// All implementations must embed UnimplementedRevocationServiceServer
// for forward compatibility.
type RevocationServiceServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedRevocationServiceServer()
}

// UnimplementedRevocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevocationServiceServer struct{}

func (UnimplementedRevocationServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRevocationServiceServer) mustEmbedUnimplementedRevocationServiceServer() {}
func (UnimplementedRevocationServiceServer) testEmbeddedByValue()                           {}

// UnsafeRevocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevocationServiceServer will
// result in compilation errors.
type UnsafeRevocationServiceServer interface {
	mustEmbedUnimplementedRevocationServiceServer()
}

func RegisterRevocationServiceServer(s grpc.ServiceRegistrar, srv RevocationServiceServer) {
	// If the following call pancis, it indicates UnimplementedRevocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevocationService_ServiceDesc, srv)
}

func _RevocationService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevocationServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevocationService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevocationServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevocationService_ServiceDesc is the grpc.ServiceDesc for RevocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "denseid.revocation.v1.RevocationService",
	HandlerType: (*RevocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _RevocationService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revocation/v1/revocation.proto",
}
