// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: revocation/v1/revocation.proto

package revocationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []byte                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Sigma         []byte                 `protobuf:"bytes,2,opt,name=sigma,proto3" json:"sigma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_revocation_v1_revocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_v1_revocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_revocation_v1_revocation_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryRequest) GetSigma() []byte {
	if x != nil {
		return x.Sigma
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRevoked     bool                   `protobuf:"varint,1,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_revocation_v1_revocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_revocation_v1_revocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_revocation_v1_revocation_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

var File_revocation_v1_revocation_proto protoreflect.FileDescriptor

const file_revocation_v1_revocation_proto_rawDesc = "" +
	"\n" +
	"\x1erevocation/v1/revocation.proto\x12\x15denseid.revocation.v1\":\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\fR\x05query\x12\x14\n" +
	"\x05sigma\x18\x02 \x01(\fR\x05sigma\".\n" +
	"\rQueryResponse\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x01 \x01(\bR\tisRevoked2g\n" +
	"\x11RevocationService\x12R\n" +
	"\x05Query\x12#.denseid.revocation.v1.QueryRequest\x1a$.denseid.revocation.v1.QueryResponseBEZCgithub.com/dense-identity/denseid/api/go/revocation/v1;revocationpbb\x06proto3"

var (
	file_revocation_v1_revocation_proto_rawDescOnce sync.Once
	file_revocation_v1_revocation_proto_rawDescData []byte
)

func file_revocation_v1_revocation_proto_rawDescGZIP() []byte {
	file_revocation_v1_revocation_proto_rawDescOnce.Do(func() {
		file_revocation_v1_revocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revocation_v1_revocation_proto_rawDesc), len(file_revocation_v1_revocation_proto_rawDesc)))
	})
	return file_revocation_v1_revocation_proto_rawDescData
}

var file_revocation_v1_revocation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_revocation_v1_revocation_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: denseid.revocation.v1.QueryRequest
	(*QueryResponse)(nil), // 1: denseid.revocation.v1.QueryResponse
}
var file_revocation_v1_revocation_proto_depIdxs = []int32{
	0, // 0: denseid.revocation.v1.RevocationService.Query:input_type -> denseid.revocation.v1.QueryRequest
	1, // 1: denseid.revocation.v1.RevocationService.Query:output_type -> denseid.revocation.v1.QueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_revocation_v1_revocation_proto_init() }
func file_revocation_v1_revocation_proto_init() {
	if File_revocation_v1_revocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revocation_v1_revocation_proto_rawDesc), len(file_revocation_v1_revocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revocation_v1_revocation_proto_goTypes,
		DependencyIndexes: file_revocation_v1_revocation_proto_depIdxs,
		MessageInfos:      file_revocation_v1_revocation_proto_msgTypes,
	}.Build()
	File_revocation_v1_revocation_proto = out.File
	file_revocation_v1_revocation_proto_goTypes = nil
	file_revocation_v1_revocation_proto_depIdxs = nil
}
